name: Build ROS2 Debian Packages

on: [push]

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
    - name: Create ROS2 Debs
      uses: automatika-robotics/create-ros-debs-action@v1
      with:
        dir-name: 'release'
        ros-versions-matrix: 'foxy'   
